### ISSUE TITLE
Cannot compile shader "shaders/skybox/vertex.glsl"

### ISSUE THREAD

**Issue by evid90** [ekpyron/pbf#2]
Hello,

I have been trying to compile and run the code. I'm using Ubuntu 14.04 with NVIDIA Quadro K4000 card.  Here is the glxinfo for OpenGL: 
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: Quadro K4000/PCIe/SSE2
OpenGL core profile version string: 4.3.0 NVIDIA 352.63
OpenGL core profile shading language version string: 4.30 NVIDIA via Cg compiler
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5.0 NVIDIA 352.63
OpenGL shading language version string: 4.50 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:

When I run the program, it keeps saying "Cannot compile shader "shaders/skybox/vertex.glsl":0(2) : error C0204: version directive must be first statement and may not be repeated". I have removed the comment and any space before the version directive but it didn't solve the error. Do you have any suggestion about this issue?

Thanks

**Comment by ekpyron** [comment]
The code has not been maintained for a while and the drivers have since changed their behavior - you should be able to fix that particular issue by removing the version statement from the shader altogether and loading it in Skybox.cpp with program.CompileShader (GL_VERTEX_SHADER, "shaders/skybox/vertex.glsl", "#version 430 core"); instead - same for the fragment shader (the reason for this issue is that ShaderProgram.cpp adds a #line statement between the header and the actual shader code that still ends up before the #version statement, which the drivers used to accept, but nowadays don't do anymore).

Most likely this won't be the only issue, though - I have the plan to update the code and bring it back to a working condition once I get around to, but don't expect it to happen anytime soon and until then it will probably be quite a challenge to get it to run correctly I'm afraid.

**Comment by ekpyron** [comment]
This should finally be solved with commit c60d3137dfb8af794dad8412af129af70590469e
